name: Build Godot Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip -O godot.zip
        unzip godot.zip -d godot
        sudo mv godot/Godot_v4.1.1-stable_linux.x86_64 /usr/local/bin/godot
        chmod +x /usr/local/bin/godot

    - name: Build Android APK
      run: |
        godot --headless --verbose --export-release Android build.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: F1Mobile-APK
        path: build.apk

