name: Build Godot Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Godot
        uses: firebelley/setup-godot@v1
        with:
          version: 4.2.2
          include-templates: true

      - name: Export Android APK
        run: |
          mkdir -p build/android
          godot --headless --verbose --export-release "Android" build/android/game.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/android/game.apk
